- name: Create unit file for Zookeper
  become: true
  template:
    src: zookeper.service.j2
    dest: /etc/systemd/system/zookeper.service

- name: Just force systemd to reread configs (2.4 and above)
  become: true
  ansible.builtin.service:
    daemon_reload: true

- name: "Restart Zookeper"
  become: true
  ansible.builtin.service:
    name: zookeper
    enabled: true
    state: restarted
