- name: Create unit file for Kafka broker
  become: true
  template:
    src: kafka-broker.service.j2
    dest: /etc/systemd/system/kafka-broker.service

- name: Copy cofnig template
  become: true
  template:
    src: server.properties.j2
    dest: "{{ kafka_unzip_path }}/kafka_2.12-3.4.0/config/server.properties"

- name: Just force systemd to reread configs (2.4 and above)
  become: true
  ansible.builtin.service:
    daemon_reload: true

- name: "Restart Broker"
  become: true
  ansible.builtin.service:
    name: kafka-broker
    enabled: true
    state: restarted
