# - name: Create kafka user
#   become: true
#   ansible.builtin.user:
#     name: kafka
#     groups: sudo
#     append: true

# - name: Make kafka user sudo without pwd
#   become: true
#   copy:
#     dest: /etc/sudoers.d/80-ansible-sudo-user
#     content: "kafka ALL=(ALL) NOPASSWD:ALL"
#     mode: 0440

- name: Update apt
  become: true
  # become_user: kafka
  # become_method: su
  apt:
    upgrade: yes
    update_cache: yes

- name: Add open JDK repo
  become: true
  # become_user: kafka
  # become_method: su
  apt_repository:
    repo: ppa:openjdk-r/ppa

- name: Install java
  become: true
  # become_user: kafka
  # become_method: su
  apt:
    name: "openjdk-11-jdk"
    update_cache: yes

- name: Download kafka3.4 tar
  become: true
  # become_user: kafka
  # become_method: su
  ansible.builtin.get_url:
    url: https://archive.apache.org/dist/kafka/3.4.0/kafka_2.12-3.4.0.tgz 
    dest: /home/ivan/kafka.tgz

- name: Unarchive kafka
  become: true
  # become_user: kafka
  # become_method: su
  ansible.builtin.unarchive:
    remote_src: true
    src: /tmp/kafka.tgz
    dest: /home/ivan/

- name: Remove archive
  become: true
  # become_user: kafka
  # become_method: su
  ansible.builtin.file:
    path: /home/ivan/kafka.tgz
    state: absent
