- name: Copy broker config template
  become: true
  template:
    src: server.properties.j2
    dest: "{{ kafka_unzip_path }}/kafka_2.12-3.8.0/config/kraft/server.properties"

- name: Create unit file for broker
  become: true
  template:
    src: kafka-broker-raft.service.j2
    dest: /etc/systemd/system/kafka-broker-raft.service

# TEMP
- name: Delete log catalog if exists
  become: true
  ansible.builtin.file:
    path: "{{ kraft_logs_dir }}"
    state: absent

- name: Create log catalog
  become: true
  shell: "{{ kafka_unzip_path }}/kafka_2.12-3.8.0/bin/kafka-storage.sh format -t {{ kafka_cluster_id }} -c {{ kafka_unzip_path }}/kafka_2.12-3.8.0/config/kraft/server.properties"

- name: Force systemd to reread configs
  become: true
  ansible.builtin.service:
    daemon_reload: true

- name: "Restart Broker"
  become: true
  ansible.builtin.service:
    name: kafka-broker-raft
    enabled: true
    state: restarted
