zookeper_local:
  hosts:
    zookeper-vm0:
      ansible_host: 10.10.10.4
      ansible_user: "ivan"
      ansible_ssh_pass: "{{ local_ssh_pwd }}"

kafka_brokers_local:
  hosts:
    broker-vm0:
      ansible_host: 10.10.10.3
      ansible_user: "ivan"
      ansible_ssh_pass: "{{ local_ssh_pwd }}"
