zookeper:
  hosts:
    zookeper-vm0:
      ansible_host: 10.10.10.6
      ansible_user: "{{ ssh_user }}"
      ansible_ssh_pass: "{{ ssh_pwd }}"

kafka_brokers:
  hosts:
    broker-vm0:
      ansible_host: 10.10.10.3
      ansible_user: "{{ ssh_user }}"
      ansible_ssh_pass: "{{ ssh_pwd }}"
